/**
 * Landing page static data arrays.
 * Separated to keep page shell and section components lean.
 */

import {
  BookOpen, Receipt, CreditCard, Landmark, Calculator, BarChart3,
  Banknote, Brain, Bot, Briefcase, Warehouse, LineChart, ClipboardCheck,
  GitMerge, Globe, ScanLine, History, KeyRound, Search, ShieldCheck,
  FileSpreadsheet, Upload, Repeat, Webhook, FileText, Layers, Archive,
  Copy, GraduationCap, Columns, MousePointerClick, PieChart, TrendingUp,
  RefreshCw, Package, Workflow,
} from 'lucide-react';

export const APP_URL = 'https://app.isaflow.co.za';

export const STATS = [
  { value: '30+', label: 'Financial Reports' },
  { value: '185+', label: 'Feature Pages' },
  { value: '110+', label: 'Business Services' },
  { value: '260+', label: 'API Endpoints' },
];

export const FEATURES = [
  { icon: BookOpen, title: 'General Ledger', desc: 'Double-entry bookkeeping with hierarchical chart of accounts, journal entries, recurring journals, cost centres, and multi-currency support.' },
  { icon: Receipt, title: 'Invoicing & AR', desc: 'Professional tax invoices, quotes, sales orders, recurring billing, credit notes, customer statements, and automated dunning.' },
  { icon: CreditCard, title: 'Accounts Payable', desc: 'Supplier invoices with 3-way matching, purchase orders, batch payments, EFT generation for all major SA banks.' },
  { icon: Landmark, title: 'Bank Reconciliation', desc: 'Import statements from FNB, Standard Bank, Nedbank, ABSA, and Capitec. 4-tier smart auto-matching with AI categorisation.' },
  { icon: Calculator, title: 'VAT & SARS', desc: 'Full VAT compliance including standard, zero-rated, exempt, and DRC VAT. VAT201, EMP201, compliance calendar, and submission tracking.' },
  { icon: BarChart3, title: '30+ Financial Reports', desc: 'Income Statement, Balance Sheet, Cash Flow, Trial Balance, Budget vs Actual, Trend Analysis, Waterfall Charts, and executive dashboards.' },
  { icon: Banknote, title: 'Payroll', desc: 'SA payroll with automatic PAYE, UIF, and SDL calculations. Payslip PDFs, IRP5 certificates, and GL auto-posting.' },
  { icon: Brain, title: 'AI Document Capture', desc: 'Vision AI extracts data from receipts, invoices, and contracts. Auto-creates invoices and journal entries with confidence scoring.' },
  { icon: Bot, title: 'Smart Categorisation', desc: 'AI-powered transaction categorisation with rules, 50+ SA merchant patterns, and machine learning. Anomaly detection built in.' },
  { icon: Briefcase, title: 'Fixed Assets', desc: 'Asset register with SARS wear-and-tear categories, depreciation scheduling, disposal tracking, and GL posting.' },
  { icon: Warehouse, title: 'Inventory', desc: 'Stock tracking with items, products, stock adjustments, pricing management, and movement reporting.' },
  { icon: LineChart, title: 'AI Analytics', desc: 'AI-generated management commentary, KPI scorecards, 3-way forecasting, ratio trends, and natural language queries.' },
  { icon: ClipboardCheck, title: 'Approval Workflows', desc: 'Configurable approval rules by document type and amount threshold. Multi-stage chains with full audit trail.' },
  { icon: GitMerge, title: 'Group Consolidation', desc: 'Multi-company management with consolidated reporting, intercompany transactions, and elimination adjustments.' },
  { icon: Globe, title: 'Customer Portal', desc: 'Self-service portal for customers to view invoices, download statements, make payments, and chat with support.' },
  { icon: ScanLine, title: 'Sage Migration', desc: 'Guided migration wizard to import chart of accounts, customers, suppliers, invoices, and opening balances from Sage.' },
  { icon: History, title: 'Full Audit Trail', desc: 'Field-level change tracking on every financial record. See who changed what, when, and the before/after values. Append-only, tamper-proof audit log.' },
  { icon: KeyRound, title: 'Two-Factor Auth', desc: 'TOTP-based 2FA with Google Authenticator support, backup codes, SMS fallback, and trusted device management for 30-day remember.' },
  { icon: Search, title: 'Command Palette', desc: 'Press Ctrl+K to instantly search across all accounts, customers, suppliers, invoices, and transactions. Keyboard shortcuts for power users.' },
  { icon: ShieldCheck, title: 'Granular Permissions', desc: 'Module-level access control with read/write/delete/export/approve per module. Account range restrictions and field masking for sensitive data.' },
  { icon: FileSpreadsheet, title: 'Custom Report Builder', desc: 'Drag-and-drop report designer. Choose data sources, columns, filters, grouping, and totals. Save templates and schedule email delivery.' },
  { icon: Upload, title: 'Excel Import Wizard', desc: '4-step import wizard for GL transactions. Upload Excel/CSV, map columns, validate with error highlighting, and import as draft or posted.' },
  { icon: Repeat, title: 'Recurring Transactions', desc: 'Automated recurring journal entries, invoices, and bills. Daily, weekly, monthly, quarterly, or annual schedules with auto-post option.' },
  { icon: Webhook, title: 'Webhooks & Integrations', desc: 'Outbound webhooks with HMAC-SHA256 signatures for CRM and third-party integration. Events for invoices, payments, customers, and more.' },
  { icon: FileText, title: 'IFRS Disclosure Notes', desc: 'Auto-generate 7 standard IFRS disclosure notes from your data — PPE schedules, receivables, payables, revenue, cash, and taxation.' },
  { icon: Layers, title: 'CaseWare Export', desc: 'Export trial balance in CaseWare-compatible CSV format. Configurable account mapping with auto-suggest. Seamless auditor handoff.' },
  { icon: Archive, title: 'Data Archiving', desc: 'Archive historical data to maintain performance. Configurable retention periods (SA Companies Act compliant). View archived data read-only.' },
  { icon: Copy, title: 'Duplicate Detection', desc: 'AI-powered duplicate detection for customers, suppliers, and items. Side-by-side comparison with merge wizard and transaction reassignment.' },
  { icon: GraduationCap, title: 'Onboarding Tour', desc: 'Interactive guided tour for new users with spotlight highlights. Contextual tooltips on complex fields. Skip and restart anytime.' },
  { icon: Columns, title: 'Debit/Credit Toggle', desc: 'Choose between split debit/credit columns or single net amount display. User preference saved and applied across all transaction views.' },
  { icon: MousePointerClick, title: 'Xero/QB/Pastel Migration', desc: 'Import from Xero, QuickBooks, and Pastel with dedicated wizards. Account mapping, customer/supplier import, and balance verification.' },
  { icon: PieChart, title: 'Cost Centres', desc: 'Allocate transactions to cost centres and business units for dimensional reporting. Track profitability by department, branch, or project.' },
  { icon: TrendingUp, title: 'Budgets & Forecasting', desc: 'Annual budgets per GL account with Budget vs Actual variance reporting. AI-powered cash flow forecasting with confidence scoring.' },
  { icon: Globe, title: 'Multi-Currency', desc: 'Multi-currency support with exchange rate management. Foreign currency transactions, revaluations, and realised/unrealised gains tracking.' },
  { icon: RefreshCw, title: 'Bank Feeds', desc: 'Live bank feeds via Stitch.money for automatic transaction syncing. Real-time sync with sync history, error tracking, and manual trigger.' },
  { icon: Banknote, title: 'Batch Payments & EFT', desc: 'Batch payment processing with EFT file generation for FNB, Standard Bank, Nedbank, ABSA, and Capitec. Pay multiple suppliers in one run.' },
  { icon: FileText, title: 'Statements & Dunning', desc: 'Customer and supplier statements with batch runs. Automated dunning letters for overdue invoices with configurable escalation schedules.' },
  { icon: Calculator, title: 'Year-End Close', desc: 'Guided year-end closing process. Auto-calculate depreciation, accrue expenses, post closing entries, and roll retained earnings forward.' },
  { icon: Briefcase, title: 'Time & Project Tracking', desc: 'Time tracking with billable rates per employee and project. Project profitability reporting with actual vs budgeted hours and margins.' },
];

export const DETAILED_FEATURES = [
  {
    badge: 'Core Accounting',
    title: 'Enterprise-grade General Ledger',
    desc: "ISAFlow's double-entry general ledger provides a rock-solid foundation for your accounting. Multi-level chart of accounts, automated journal entries from all modules, fiscal period management, and real-time balance tracking.",
    bullets: ['Hierarchical chart of accounts with 57+ default accounts', 'Auto-balanced journal entries enforced by database triggers', 'Cost centres & business units for dimensional reporting', 'Multi-currency with exchange rate management', 'Recurring journal templates', 'Opening balances & year-end closing'],
    imgKey: 'general-ledger',
  },
  {
    badge: 'Accounts Receivable',
    title: 'Get paid faster with smart invoicing',
    desc: 'Create professional tax invoices, set up recurring billing, and track every rand. Automated dunning keeps your cash flow healthy while the customer portal gives clients self-service access.',
    bullets: ['Professional invoice PDF generation & email delivery', 'Quotes → Sales Orders → Invoices workflow', 'Recurring invoices with flexible schedules', 'Credit notes, write-offs & payment allocation', 'Customer statements & batch statement runs', 'AR aging analysis with debtors manager dashboard'],
    imgKey: 'invoicing',
  },
  {
    badge: 'Banking',
    title: 'Bank reconciliation on autopilot',
    desc: 'Import statements from FNB, Standard Bank, Nedbank, ABSA, Capitec, or any OFX/QIF file. Our 4-tier smart matching engine automatically categorises and reconciles transactions with confidence scoring.',
    bullets: ['7+ bank statement formats supported', '4-tier auto-matching (rules → reference → amount+date → AI)', 'AI-powered smart categorisation with anomaly detection', 'Categorisation rules engine with live preview', 'Bank feeds via Stitch.money for real-time sync', 'Batch payments with EFT file generation for all major SA banks'],
    imgKey: 'banking',
  },
  {
    badge: 'AI-Powered',
    title: 'Intelligence built into every workflow',
    desc: 'ISAFlow uses Vision AI and machine learning to automate tedious accounting tasks. Capture a receipt, and watch it become a journal entry. Upload a supplier invoice, and it auto-matches to your purchase order.',
    bullets: ['Vision AI document extraction (receipts, invoices, contracts)', 'Auto-invoice creation from captured documents', '3-way matching: PO + delivery note + invoice', 'AI-generated management commentary on financials', 'Natural language queries against your data', 'Continuous close automation with smart categorisation'],
    imgKey: 'ai-features',
  },
  {
    badge: 'Tax Compliance',
    title: 'SARS-ready from day one',
    desc: 'Built specifically for South African tax compliance. Automatic VAT calculations on every transaction, VAT201 return generation, EMP201 payroll submissions, and a compliance calendar to never miss a deadline.',
    bullets: ['9 VAT types (standard 15%, zero-rated, exempt, DRC, etc.)', 'VAT201 return auto-generation', 'EMP201 employee tax returns with IRP5 certificates', 'SARS submission tracking with full history', 'Compliance calendar with alerts for due dates', 'DRC VAT support for qualifying transactions'],
    imgKey: 'sars',
  },
  {
    badge: 'Analytics & Reporting',
    title: '30+ reports with a custom report builder',
    desc: 'From trial balances to AI-powered 3-way forecasts, ISAFlow gives you the insights you need. Plus a drag-and-drop custom report builder to create exactly the report you want — with saved templates and scheduled email delivery.',
    bullets: ['Income Statement, Balance Sheet, Cash Flow, Trial Balance', 'Budget vs Actual with variance analysis', 'Custom Report Builder — drag-and-drop columns, filters, grouping', 'KPI scorecard with traffic-light scoring', 'IFRS disclosure note auto-generation (7 note types)', 'CaseWare-compatible trial balance export for auditors'],
    imgKey: 'reports',
  },
  {
    badge: 'Security & Governance',
    title: 'Enterprise-grade trust and compliance',
    desc: 'ISAFlow delivers the security and governance features that professional accountants demand. Full audit trail, two-factor authentication, granular permissions, and data archiving — everything needed to meet regulatory requirements and earn client confidence.',
    bullets: ['Field-level audit trail — who changed what, when, with before/after values', 'Two-factor authentication (TOTP + backup codes + trusted devices)', 'Module-level permissions with read/write/delete/export/approve controls', 'Configurable approval workflows by document type and amount', 'Data archiving with SA Companies Act compliant retention periods', 'Command palette (Ctrl+K) and keyboard shortcuts for power users'],
    imgKey: 'security',
  },
  {
    badge: 'Migration & Integration',
    title: 'Switch from any system in minutes',
    desc: 'ISAFlow makes migration painless with dedicated import wizards for Sage, Xero, QuickBooks, and Pastel. Plus webhook integrations and Excel import for ongoing data connectivity.',
    bullets: ['Sage, Xero, QuickBooks & Pastel migration wizards', 'Excel/CSV import wizard with column mapping and validation', 'Bank PDF parsers for FNB, Standard Bank, Nedbank, ABSA, Capitec', 'Outbound webhooks with HMAC-SHA256 for CRM integration', 'Recurring transaction templates (daily to annually)', 'Duplicate detection and merge wizard for data quality'],
    imgKey: 'migration',
  },
];

export const PRICING_TIERS = [
  {
    name: 'Starter',
    price: 'R 499',
    period: '/month',
    desc: 'Perfect for sole proprietors and small businesses just getting started.',
    features: [
      'Full General Ledger',
      'Invoicing, Quotes & Statements',
      'Bank Reconciliation (1 bank)',
      'VAT Returns & SARS Compliance',
      '10 Financial Reports',
      'Inventory & Items',
      'Full Audit Trail',
      'Two-Factor Authentication',
      'Command Palette & Keyboard Shortcuts',
      'Customer Statements & Dunning',
      'Year-End Close Wizard',
      'Up to 2 users',
      'Email support',
    ],
    cta: 'Start Free Trial',
    popular: false,
  },
  {
    name: 'Professional',
    price: 'R 999',
    period: '/month',
    desc: 'For growing businesses that need full accounting power and automation.',
    features: [
      'Everything in Starter, plus:',
      'Unlimited bank accounts & bank feeds',
      'AI Smart Categorisation & Anomaly Detection',
      'AI Document Capture (Vision AI)',
      'Recurring Invoices & Journals',
      'Batch Payments & EFT Generation',
      'All 30+ Reports & Executive Dashboard',
      'Custom Report Builder',
      'Customer Portal',
      'Fixed Assets & Depreciation',
      'Approval Workflows',
      'Granular Module Permissions',
      'Excel Import Wizard',
      'Duplicate Detection & Merge',
      'Recurring Transaction Templates',
      'Multi-Currency & Exchange Rates',
      'Bank Feeds (Stitch.money)',
      'Time & Project Tracking',
      'Up to 10 users',
      'Priority support',
    ],
    cta: 'Start Free Trial',
    popular: true,
  },
  {
    name: 'Enterprise',
    price: 'R 2,499',
    period: '/month',
    desc: 'For accounting firms and multi-entity businesses with advanced needs.',
    features: [
      'Everything in Professional, plus:',
      'Multi-entity / Group Consolidation',
      'Payroll with PAYE/UIF/SDL & IRP5',
      'SARS eFiling (VAT201 + EMP201)',
      'AI Management Commentary & Forecasting',
      '3-Way Forecast (P&L + BS + Cash Flow)',
      'IFRS Disclosure Note Generator',
      'CaseWare Export & Account Mapping',
      'Data Archiving & Retention Engine',
      'Webhooks for CRM Integration',
      'Sage, Xero, QuickBooks & Pastel Migration',
      'Cost Centres & Business Units',
      'Budgets with Variance Analysis',
      'AI Cash Flow Forecasting',
      'Continuous Close Automation',
      'Unlimited users',
      'Dedicated account manager',
    ],
    cta: 'Contact Sales',
    popular: false,
  },
];

export const TESTIMONIALS = [
  { name: 'Thandi Molefe', role: 'CFO, TechBridge Solutions', quote: 'ISAFlow has transformed how we handle our accounting. The bank reconciliation alone saves us 15 hours a month. The SARS compliance features give us peace of mind.', stars: 5 },
  { name: 'Johan van der Merwe', role: 'Owner, VDM Construction', quote: 'Migrating from Sage was seamless. The smart categorisation learns our patterns and now auto-allocates 90% of our bank transactions. Incredible time saver.', stars: 5 },
  { name: 'Priya Naidoo', role: 'Practice Manager, Naidoo & Associates', quote: 'Managing multiple client entities is effortless with ISAFlow. The approval workflows and audit trail give our clients confidence in our processes.', stars: 5 },
];

export const FAQ_ITEMS = [
  { q: 'Is ISAFlow SARS-compliant?', a: 'Yes. ISAFlow is built from the ground up for South African tax compliance. It supports all VAT types (standard 15%, zero-rated, exempt, DRC), generates VAT201 and EMP201 returns, tracks SARS submission deadlines, and maintains a field-level audit trail on every financial record.' },
  { q: 'Can I import data from Sage or other systems?', a: 'Absolutely. ISAFlow includes dedicated migration wizards for Sage, Xero, QuickBooks, and Pastel. Import your chart of accounts, customers, suppliers, and opening balances with automatic account mapping and post-migration balance verification.' },
  { q: 'Which banks are supported for statement import?', a: 'ISAFlow supports statement imports from FNB, Standard Bank, Nedbank, ABSA, and Capitec in CSV and PDF formats, plus OFX and QIF for other banks. Bank feeds via Stitch.money provide automatic transaction syncing. Our AI auto-detects the bank format.' },
  { q: 'How does the audit trail work?', a: 'Every change to financial data is recorded with who made the change, when, and the exact before/after values for each field. The audit trail is append-only and tamper-proof. You can filter by entity, user, action, and date range, and export the full log to Excel.' },
  { q: 'Is my data secure?', a: 'Enterprise-grade security: two-factor authentication (TOTP + backup codes), granular module-level permissions, field masking for sensitive data, SSL/TLS encryption, bcrypt password hashing, and signed JWT sessions. Plus configurable approval workflows for high-value transactions.' },
  { q: 'Can I create custom reports?', a: 'Yes! The Custom Report Builder lets you choose any data source, drag-and-drop columns, add filters and grouping, and see results live. Save templates for reuse and schedule reports for email delivery. Plus 30+ pre-built reports and IFRS disclosure note auto-generation.' },
  { q: 'Can I try ISAFlow for free?', a: 'Yes! Every plan comes with a 14-day free trial — no credit card required. You get full access to all features in your selected tier so you can evaluate ISAFlow with your real data before committing.' },
  { q: 'Does ISAFlow work with CaseWare?', a: 'Yes. ISAFlow exports trial balances in CaseWare-compatible CSV format. You can configure account mappings with auto-suggest based on account types, and the mapping is saved for reuse each financial year. Seamless auditor handoff without manual data re-entry.' },
];
